### ISSUE TITLE
OOM with Default memory settings from manifest

### ISSUE THREAD

**Issue by ashwatthb** [alexellis/registry-creds#15]
**Describe the bug**
Experiencing OOMKilled with out of memory when applying default manifest 

**To Reproduce**

**Expected behavior**

**Screenshots or console output**

**Operating system and version:**

**List all possible solutions, and your suggested option**
- increase the default requests and Limits 
- Add Helm charts where individuals can override the values.

**Additional context**
We don't want to download the file locally and update the manifest as we would like to keep up to date with latest changes from this manifest.

**Comment by alexellis** [comment]
Hi there, I'll increase the limit, but I've not run into this myself.

How much memory did you configure your local version with to keep it stable? The current limit is 30Mi

Alex

**Comment by alexellis** [comment]
/lock: inactive, raise your own issue as a GitHub Sponsor
