### ISSUE TITLE
readme says uses $username but export cant change it 

### ISSUE THREAD

**Issue by si458** [alexellis/registry-creds#17]
**Describe the bug**
on mac you cant change the $USERNAME value for some reason
so when you copy+paste the readme code it deploys using the laptops username instead of what you set

**To Reproduce**
```
Simon@SiMacBookPro Kubernetes % echo $USERNAME
Simon
Simon@SiMacBookPro Kubernetes % export USERNAME=si458
Simon@SiMacBookPro Kubernetes % echo $USERNAME
Simon
Simon@SiMacBookPro Kubernetes % 
```

**Expected behavior**
`$USERNAME` was to be set as my dockerhub user which it wasnt

**Screenshots or console output**
```
Simon@SiMacBookPro Kubernetes % echo $USERNAME
Simon
Simon@SiMacBookPro Kubernetes % export USERNAME=si458
Simon@SiMacBookPro Kubernetes % echo $USERNAME
Simon
Simon@SiMacBookPro Kubernetes % 
```

**Operating system and version:**
Mac 10.15.7

**List all possible solutions, and your suggested option**
change value in read to say `UN` instead of `USERNAME`

**Additional context**

**Comment by alexellis** [comment]
/lock: inactive, raise your own issue as a GitHub Sponsor
