### ISSUE TITLE
Add version and commit SHA to the binary

### ISSUE THREAD

**Issue by alexellis** [alexellis/registry-creds#21]
We should add version and commit SHA to the binary just like with the inlets-operator in its [Dockerfile](https://github.com/inlets/inlets-operator/blob/master/Dockerfile) and [GH Action](https://github.com/inlets/inlets-operator/blob/master/.github/workflows/publish.yaml)

Having a version printed out on start-up helps with user issues and knowing which version is being run.

**Comment by alexellis** [comment]
/add label: good first issue, help wanted

**Comment by developer-guy** [comment]
I'm a volunteer for this issue.

**Comment by alexellis** [comment]
/lock: inactive, raise your own issue as a GitHub Sponsor
