### ISSUE TITLE
Propose to work on feature - Propagate alterations/updates to the primary ClusterPullSecret

### ISSUE THREAD

**Issue by hanks** [alexellis/registry-creds#26]
**Is your feature request related to a problem? Please describe.**
As mentioned  in TODO list:

* Propagate alterations/updates to the primary ClusterPullSecret in each namespace when the secret value changes (the work-around is to delete and re-create the ClusterPullSecret)

Now there is no feature to do the automation secret update, which is not convenient, even that we have the workaround.

**Describe all possible solutions, and which you suggest**

Now have one idea is similar to other watchers, like namespace, serviceaccount. We could create a new watcher for seed secret, and when it is updated, the controller will get the event, to re-trigger reconciling for ClusterPullSecretReconciler to update all the secrets in the namespaces.

**Describe alternatives and workarounds that you've considered**
None

**Additional context**
None

**Comment by hanks** [comment]
@alexellis Hi, is this propose looking good to you? I just followed the CONTRIBUTOR doc that want to ask for working some features here, not sure missing some description in the issue.

**Comment by hanks** [comment]
@alexellis Hi, I have created a runable branch in my local, is it fine to create the PR?

**Comment by alexellis** [comment]
Hi @hanks 

> Describe alternatives and workarounds that you've considered

There is a workaround in the README for rotating. You simply delete and recreate the ClusterPullSecret.

Why do you feel that wouldn't work for your team?

Alex

**Comment by alexellis** [comment]
/lock: inactive, raise your own issue as a GitHub Sponsor
