### ISSUE TITLE
Exclude namespace(s) in configuration instead of annotations

### ISSUE THREAD

**Issue by przemolb** [alexellis/registry-creds#30]
Currently if you want to exclude particular namespace(s) you need to add annotation:
```
kubectl annotate ns mynamespace alexellis.io/registry-creds.ignore=1
```
In case there are hundreds or more namespaces it requires to develop script with list of namespaces which should have that annotation added.
In addition to the above (and I think it would be more scalable solution) add white/black list to the config YAML file specifying which namespaces should or shouldn't have secrets created. Ideally with regexp so we could add i.e.: all namespaces starting with `test-` should have secret(s) created.

**Comment by alexellis** [comment]
How many namespaces do you have per cluster? Is this an actual problem you have?

**Comment by przemolb** [comment]
At the moment of writing we don't have that many namespaces. But we are soon going to have hundreds (or more) short lived namespaces. The logic added to the operator would greatly improve its scalability.

**Comment by alexellis** [comment]
Let's wait and see how it copes when you get there? I'll close this for now, re-open if performance shows itself to be an issue at your increased scale. Keeping the scope smaller, and easier to maintain means I can create a better experience for everyone.

You're welcome to become a GitHub Sponsor if you'd like to support the tool

**Comment by przemolb** [comment]
I started using kyverno for this functionality.

**Comment by alexellis** [comment]
/lock: inactive, raise your own issue as a GitHub Sponsor
