### ISSUE TITLE
Image tags become unavailable

### ISSUE THREAD

**Issue by dfateyev** [alexellis/registry-creds#39]
**Describe the bug**
Registry-creds tags become unavailable on "ghcr.io":
```
$ docker pull ghcr.io/alexellis/registry-creds:0.2.6
Error response from daemon: manifest unknown

$ docker pull ghcr.io/alexellis/registry-creds:0.2.7
Error response from daemon: manifest unknown

$ docker pull ghcr.io/alexellis/registry-creds:0.3.1-1
Error response from daemon: manifest unknown
```

**To Reproduce**
Try to pull some image tags which worked before

**Expected behavior**
Image tag pull expected to be working

**Are you a GitHub Sponsor (Yes/No?)** No

**Comment by alexellis** [comment]
Hi, the release is as follows:

https://github.com/alexellis/registry-creds/releases/tag/0.3.1-rc1

If you're using this project, become a sponsor via GitHub. You can pick any monthly amount you feel represents the value you are getting from my work.

https://github.com/sponsors/alexellis

```
docker pull ghcr.io/alexellis/registry-creds:0.3.1-rc1
0.3.1-rc1: Pulling from alexellis/registry-creds
Digest: sha256:09e8ab0eaf57f721ad044787e85d965b4f40a9897401d9e5b00d951b430af011
Status: Image is up to date for ghcr.io/alexellis/registry-creds:0.3.1-rc1
ghcr.io/alexellis/registry-creds:0.3.1-rc1

```

Regards,

Alex
