### ISSUE TITLE
k8s 1.26 Support

### ISSUE THREAD

**Issue by dhanushsure** [alexellis/registry-creds#40]
**Describe the bug**
We are upgrading from k8s 1.21 -> 1.26 soon. I recently ran a scan of packages that need to be updated/upgraded. Here are the results:

CustomResourceDefinition   <undefined>   clusterpullsecrets.ops.alexellis.io   apiextensions.k8s.io/v1beta1        apiextensions.k8s.io/v1 (1.16.0)

These api versions need to be upgraded.

**To Reproduce**
kubent {cluster}

**Expected behavior**
kubent doesnt pick up any api deprecations

**Are you a GitHub Sponsor (Yes/No?)**
NO

Issues from sponsors get prioritised and a quicker response.

Check at: https://github.com/sponsors/alexellis
- [ ] Yes
- [X ] No

**Screenshots or console output**

**Operating system and version:**

**List all possible solutions, and your suggested option**
I have a PR in fork that I can raise when issue gets accepted. Can tag new version 

**Additional context**

**Comment by alexellis** [comment]
Hi @dhanushsure thanks for your interest here.

Let me see how I can help here.

But first, in order to allocate the time to work on this for you. Who is "we"? It helps to known which commercial teams and companies are relying on this project.

Regards,

Alex

**Comment by alexellis** [comment]
I tried running on K8s 1.26 and it worked without any issues.

Thanks for the interest.

Alex

**Comment by alexellis** [comment]
Whilst it wasn't necessary, I upgraded all internal packages to Go 1.26 and published a newer version:

https://github.com/alexellis/registry-creds/releases/tag/0.3.2-rc1

**Comment by alexellis** [comment]
@RicardoNalesAmato @kendrickclark @arnaud-zg @dylandjian @moonape1226 you may want to switch to the latest version of our build, or rebase your commercial forks of this project.

Alex

**Comment by dhanushsure** [comment]
Awesome thanks so much!

**Comment by alexellis** [comment]
No worries @dhanushsure 

I'm looking for people to help support this [work via GitHub Sponsors](https://github.com/sponsors/alexellis). Have a look, and if you find this project useful, I'd suggest finding what tier fits your support needs and usage.

**Comment by moonape1226** [comment]
Thanks for sharing!
