### ISSUE TITLE
What is `delete` `namespace` permission used for?

### ISSUE THREAD

**Issue by yujunz** [alexellis/registry-creds#47]
https://github.com/alexellis/registry-creds/blob/77b2b0b0d088a477428bbc6e35ed56b503279903/config/rbac/role.yaml#L13

What's the use case of `delete` `namespace` permission in registry-creds? Is it within the minimal privilege required?

**Comment by alexellis** [comment]
Hi, I don't think that create/update/delete are needed for namespaces - namespace_watcher.go is the main place where interactions take place with namespaces, it should be watch/get/list that is needed.

**Comment by alexellis** [comment]
I removed these entries.
